"""Create memos table

Revision ID: 2ca1535bede9
Revises: 
Create Date: 2025-12-26 11:18:10.306315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca1535bede9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='메모 제목'),
    sa.Column('content', sa.Text(), nullable=True, comment='메모 내용'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_id'), 'memos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memos_id'), table_name='memos')
    op.drop_table('memos')
    # ### end Alembic commands ###
